# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: musa_blog_development
  pool: 5

development:
  <<: *default
  database: musa_blog_development

production:
  <<: *default
  username: musa_blog
  password: <%= ENV['MUSA_BLOG_DATABASE_PASSWORD'] %>
  database: musa_blog_production
